export const SET_ACTIVE_DRAG = 'SET_ACTIVE_DRAG';
export const UPDATE_ACTIVE_DRAG = 'UPDATE_ACTIVE_DRAG';
export const RESET_ACTIVE_DRAG = 'RESET_ACTIVE_DRAG';
export const APPEND_TABLE_TO_ACTIVE_DIAGRAM = 'APPEND_TABLE_TO_ACTIVE_DIAGRAM';
export const UPDATE_TABLE_OF_ACTIVE_DIAGRAM = 'UPDATE_TABLE_OF_ACTIVE_DIAGRAM';
export const REMOVE_TABLE_FROM_ACTIVE_DIAGRAM = 'REMOVE_TABLE_FROM_ACTIVE_DIAGRAM';
export const APPEND_RELATIONSHIP_TO_ACTIVE_DIAGRAM = 'APPEND_RELATIONSHIP_TO_ACTIVE_DIAGRAM';
export const REMOVE_RELATIONSHIP_FROM_ACTIVE_DIAGRAM = 'REMOVE_RELATIONSHIP_FROM_ACTIVE_DIAGRAM';